### ISSUE TITLE
Error related to Multipart uninitialized constant DEFAULT_BOUNDARY

### ISSUE THREAD

**Issue by prettyGoo** [hodinkee/apple-news-rb#12]
**Gem versions:**
`ruby: 2.5.3`
`rails 6.0.1`
`multipart-post 2.1.1`
`apple-news-rb 0.5.1`

When I attempt to create or update an article using code like this
```ruby
article = AppleNews::Article.new(article_id)
article.document.title = "New Title!"
article.save!
```
I get next error:
`Name error: uninitialized constant Net::HTTP::Post::Multipart::DEFAULT_BOUNDARY`

I guess, multipart-post version somehow is the reason of this issue, but probably somebody have other suggestions why this is happening and how it is possible to fix it.

P.S. By the way, it seems there is no problems with any get and `delete!` methods.

**Comment by prettyGoo** [comment]
`DEFAULT_BOUNDARY` seems to be removed from `multipart-post`, at least at its master

**Comment by jasonknebel** [comment]
@prettyGoo Did you have any luck fixing this? I just ran into the same problem.

**Comment by prettyGoo** [comment]
@jasonknebel HI! Firstly, I tried to modify this gem with something like this
```
def boundary
 @boundary ||= "--#{SecureRandom.alphanumeric(60)}"
end
```

But I still didn't manage to send `POST` request (only GET or DELETE were accepted by Apple), so I had to implement access to Apple News API myself using some parts of this gem and this [https://developer.apple.com/documentation/apple_news/apple_news_api_tutorial](url) Python scripts as the examples.

Even though I am not sure what causes problems with this gem (if boundary problem is fixed), I can suggest that this is because of how request body is formed. I did it like this
  ```
def build_content_body(action, json, revision_number)
    body = "--#{boundary}\r\n"

    if action == 'update'
      body += "Content-Type: application/json\r\n"
      body += "Content-Disposition: form-data; name=metadata\r\n\r\n"
      body += JSON.dump(data: { revision: revision_number })
      body += "\r\n--#{boundary}\r\n"
    end

    body += "Content-Type: application/json\r\n"
    body += "Content-Disposition: form-data; filename=article.json; size=#{json.bytesize}\r\n\r\n"
    body += json
    body += "\r\n--#{boundary}--"

    body
end
```
Also take note of `\r `and `\n`. The amount of times they are used in string interpolation seems to be important for Apple

And, please, let me know if you come across a solution which fixes this gem problem

**Comment by jasonknebel** [comment]
@prettyGoo Hello! Thanks for responding with such a detailed response. I am still working through this. Like you, I'm not sure where this issue comes from and I'm not convinced it's even in the AppleNews gem. I'll keep you posted with what I find!

**Comment by jasonknebel** [comment]
@prettyGoo Have you tried upgrading ruby or the gems? As I continued with my upgrade of rails 5.0 -> 5.1, this seems to have gone away. I made a mistake earlier, not realizing we have been using our own fork of this gem at version 0.5.1.
