### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by twelvelabs** [hodinkee/apple-news-rb#4]
I'd like to use this gem in a project at work, but it would need [to explicitly state the license it's using](https://help.github.com/articles/licensing-a-repository/). Note that GH has [a handy UI](https://help.github.com/articles/adding-a-license-to-a-repository/) that will let you select a license file from a dropdown to make it easy, or if you just let me know your preference I'll happily submit a PR.

**Comment by twelvelabs** [comment]
ping @meltingice

**Comment by meltingice** [comment]
I just got back from vacation, will update soon.
		
		

		--
Ryan LeFevre (@meltingice)
Sr. Software Engineer
HODINKEE
	




On Mon, Aug 28, 2017 at 10:59 AM -0400, "Skip Baney" <notifications@github.com> wrote:












ping @meltingice

**Comment by twelvelabs** [comment]
No worries. Again, if you're fine with a standard MIT license I can have a PR for you in ~ 5 minutes 😄.

**Comment by meltingice** [comment]
Yes MIT is fine, thanks!
		
		

		--
Ryan LeFevre (@meltingice)
Sr. Software Engineer
HODINKEE
	




On Mon, Aug 28, 2017 at 4:33 PM -0400, "Skip Baney" <notifications@github.com> wrote:












No worries. Again, if you're fine with a standard MIT license I can have a PR for you in ~ 5 minutes 😄.

**Comment by meltingice** [comment]
Looks like I beat you to it. Added it.
